### ISSUE TITLE
Title Screen Gradient 

### ISSUE THREAD

**Issue by jon-powell** [real-art/vertical-market-issues#54]
Green gradient is clearly visible on client's screen. Either our files or their monitors aren't picking up full spectrum of color. Will need to look at files to determine.

**Comment by dustinclinard** [comment]
Easiest way for us to troubleshoot would be to have them send us a screenshot from the PC and a picture from their phone. Once we compare the 2 we'll know if it's on us or the monitor.

**Comment by LValko** [comment]
FIXED!
